%%//Phase Reversal//%%

clc;
clear all;
close all;
t=imread('D:\Sri\DIP images\aaa.bmp');
a=imresize(t,[250 250]);
subplot(4,3,1);
imshow(a);
title('original image1');
s=imread('D:\Sri\DIP images\man.bmp');
b=imresize(s,[250 250]);
subplot(4,3,2);
imshow(b);
title('original image2');
a1=fft2(a);
subplot(4,3,3);
imshow(a1);
title('fft of first image');
b1=fft2(b);
subplot(4,3,4);
imshow(b1);
title('fft of second image');
mag1=abs(a1);
subplot(4,3,5);
imshow(mag1);
title('mag of first image');
mag2=abs(b1);
subplot(4,3,6);
imshow(mag2);
title('mag of second image');
pha1=angle(a1);
subplot(4,3,7);
imshow(pha1);
title('phase of first image');
pha2=angle(b1);
subplot(4,3,8);
imshow(pha2);
title('phase of second image');
newa=mag1.*(exp((1j)*pha2));
subplot(4,3,9);
imshow(newa);
title('phase reversal of first image');
newb=mag2.*(exp((1j)*pha1));
subplot(4,3,10);
imshow(newb);
title('phase reversal of second image');
invfft1=ifft2(newa);
subplot(4,3,11);
imshow(invfft1);
title('ifft of first image');
invfft2=ifft2(newb);
subplot(4,3,12);
imshow(invfft2);
title('ifft of second image');
